### ISSUE TITLE
Feature request: Custom colors

### ISSUE THREAD

**Issue by brightvalley** [GoldenGnu/jeveassets#115]
Is it possible to change the color of some items in the list? I would like to change the background color of BPOs from yellow to dark blue and of BPCs to light blue, matching the color scheme in the game.

**Comment by GoldenGnu** [comment]
## Todo

### Iteration 1
- [ ] i18n
   - JColorTable
   - ColorsTableFormat
   - JSimpleColorPicker
   - ColorEntry
   - ColorSettingsPanel
- [ ] Load/Save current color scheme
- [ ] Fix settings table size

### Iteration 2 
- [ ] Load/Save color schemes
   - Ask to overwrite existing non-default colors
   - Predefined color schemes:
      - At least one with colorblind friendly colors
      - jEveAssets default (default if `FLAG_STRONG_COLORS` is false)
      - jEveAssets default strong colors (default if `FLAG_STRONG_COLORS` is true)
- [ ] Maybe: Replace `Color` constants with `Colors` constants

**Comment by GoldenGnu** [comment]
Released in 6.4.0

**Comment by brightvalley** [comment]
Many thanks for your work. May I ask, which category do blueprint copies fall under?

**Comment by GoldenGnu** [comment]
There is no blueprint copy category, because, I only made existing colors customizable. BPC never had a color (apparently?), please make a new issue to request BPC colors (It's pretty easy to add, so, it will most likely be in the next feature release, given you make a issue for it).
