### ISSUE TITLE
Dark Themes

### ISSUE THREAD

**Issue by Darkchyylde** [GoldenGnu/jeveassets#66]
Is there any way we could get a "night mode" or some way to make the main window darker?

**Comment by GoldenGnu** [comment]
This will not be support "out of the box". But, it's possible to change the Swing L&F jEveAssets uses from the command line.

Syntax:
`java -Dswing.defaultlaf=[LOOK AND FEEL CLASS] -jar jeveassets.jar`

Example:
`java -Dswing.defaultlaf=om.sun.java.swing.plaf.nimbus.NimbusLookAndFeel -jar jeveassets.jar`

Here is a few you can try with (not all of them are support on all platforms):
`com.sun.java.swing.plaf.nimbus.NimbusLookAndFeel`
`javax.swing.plaf.metal.MetalLookAndFeel`
`com.sun.java.swing.plaf.gtk.GTKLookAndFeel`
`com.sun.java.swing.plaf.motif.MotifLookAndFeel`

You can google to find more look and feels, if you like.

**Comment by GoldenGnu** [comment]
Dark theme is possible with: https://www.formdev.com/flatlaf

**Comment by GoldenGnu** [comment]
### ToDo
- [x] Statusbar
- [x] Tracker
- [ ] Date Picker
- [ ] Values
- [ ] Isk
  - [ ] Total
- [ ] Tree
- [ ] Stockpile
  - [ ] StockpileItemDialog -> JTextField jCountMinimum
  - [ ] StockpileDialog ->JTextField jName
  - [ ] Total
  - [ ] Separator Cell
  - [ ] Table
- [ ] FilterPanel ->JTextField jText
- [ ] Materials
  - [ ] Separator Cell
- [ ] Contracts
  - [ ] Spectator Cell
  - [ ] Table
- [ ] Ship Fittings
  - [ ] Separator Cell
- [ ] Reprocessed
  - [ ] Total
  - [ ] Separator Cell
- [ ] Account manager
  - [ ] Spectator Cell
- [ ] Color Settings
  - [ ] Separator Cell

### Maybe?
- [ ] Overview?
- [ ] Journal?
- [ ] Transactions?
- [ ] Market Orders?
- [ ] Routing?
- [ ] Items?

**Comment by GoldenGnu** [comment]
Released in 6.5.0

**Comment by goldhaxx** [comment]
This is how you enable dark mode in the app:

![image](https://github.com/GoldenGnu/jeveassets/assets/1616671/4d02df2b-b009-448a-9612-229eca0cebde)

![image](https://github.com/GoldenGnu/jeveassets/assets/1616671/685c813a-0030-4cca-a1bc-c65ded570090)
